---
# required installation before initializing cluster

- name: set Shekan in /etc/resolv.conf
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf

- name: disable swap
  shell: |
        sudo swapoff -a
        sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

# - name: Create containerd config file
#   file:
#     path: "/etc/modules-load.d/containerd.conf"
#     state: "touch"

- name: add config
  copy:
    src: containerd.conf
    dest: /etc/modules-load.d/containerd.conf